### ISSUE TITLE
exo-clean: unable to delete (cannot be forced)

### ISSUE THREAD

**Issue by cheahuychou** [Originate/exosphere#325] opened 2017-07-11 00:06 UTC
Got this strange error when running the `exo-clean` tests on my machine. How can the image be dangling if it is being used?
```
  Scenario: cleaning a machine with both dangling and non-dangling Doker images   # features/clean.feature:13
    Given my machine has both dangling and non-dangling Docker images and volumes # clean_feature_context.go:73 -> github.com/Originate/exosphere/exo-go/test_helpers.CleanFeatureContext.func2
    When running "exo clean" in the terminal                                      # shared_feature_context.go:59 -> github.com/Originate/exosphere/exo-go/test_helpers.SharedFeatureContext.func5
    exit status 2
Command errored with output: We are about to clean up your Docker workspace!

panic: Error response from daemon: conflict: unable to delete 2dd38a9ef428 (cannot be forced) - image is being used by running container 8521071215bd

goroutine 1 [running]:
github.com/Originate/exosphere/exo-go/src/cmd.glob..func3(0x1677a00, 0x1697a30, 0x0, 0x0)
[truncated]
```

**Comment by hugoesthere** [comment] 2017-07-11 17:25
Yes, I've seen this as well. I've also seen a couple tests where it fails to remove all dangling images - I wonder if we're listing the dangling images incorrectly or something.

**Comment by charlierudolph** [comment] 2017-07-11 22:29
Next time someone runs into this please pull @hugobho or I over to investigate the cause a bit more.  Mainly look into the image and container see if we can determine the cause

**Comment by charlierudolph** [comment] 2017-08-03 22:36
Closing this in favor of #320 as stopping and removing the containers will hopefully resolve this issue.

**Closed as completed by charlierudolph** 2017-08-03 22:36 UTC
